seed:
  value: 0

# trainer
n_epochs: 
  value: 200
log_every:
  value: 50

# model
arch:
  value: ResNet18
norm_type: 
  value: bn
model_kwargs: 
  value: {}

# optimizer
# lr: 
#   value: 0.1
weight_decay: 
  value: 5.e-4

# data
data_dir: 
  value: ../datasets/CIFAR10

batch_size: 
  value: 128

watch_model:
  value: false