seed:
  value: 0

# trainer
n_epochs: 
  value: 100
log_every:
  value: 50

# model
arch:
  value: resnet20
norm_type: 
  value: regn
model_kwargs: 
  value: {"r": 0.6, "group_size": 2}

# optimizer
lr: 
  value: 0.1
weight_decay: 
  value: 5.e-4

# data
data_dir: 
  value: ../datasets/CIFAR10

batch_size: 
  value: 128

watch_model:
  value: false