seed:
  value: 0

# trainer
n_epochs: 
  value: 5
save_dir: 
  value: null
log_every:
  value: 1

# model
arch: 
  value: resnet18
norm_type: 
  value: ln
model_kwargs: 
  value: {"r": 1.0}

# optimizer
lr: 
  value: 0.1
weight_decay: 
  value: 5.e-4

# data
data_dir: 
  value: ../datasets/CIFAR10

batch_size: 
  value: 16

watch_model:
  value: false