seed: 42

# trainer
max_epochs: 100
log_every_n_steps: 50
save_dir: /content/drive/MyDrive/logs

# model
arch: resnet18
norm_type: bn

# data
data_dir: /content/data
normalize: true
val_split: 5000
num_workers: 2
batch_size: 256

ckpt_path: null
