seed: 42

# trainer
max_epochs: 100
log_every_n_steps: 50
save_dir: /content/drive/MyDrive/logs

# model
arch: resnet18
norm_type: gn
model_kwargs: {}

# optimizer
lr: 0.1
weight_decay: 5e-4

# data
data_dir: /content/data
num_workers: 2
batch_size: 128

ckpt_path: null
